function twinkleTwinkle(){
    const now = Tone.now()
    sampler.triggerAttackRelease("G3", "8n", now)
    sampler.triggerAttackRelease("G3", "4n", now + 0.5)
    sampler.triggerAttackRelease("D4", "8n", now + 1)
    sampler.triggerAttackRelease("D4", "4n", now + 1.5)
    sampler.triggerAttackRelease("E4", "8n", now + 2)
    sampler.triggerAttackRelease("E4", "8n", now + 2.5)
    sampler.triggerAttackRelease("D4", "8n", now + 3)

    sampler.triggerAttackRelease("C4", "8n", now + 4)
    sampler.triggerAttackRelease("C4", "4n", now + 4.5)
    sampler.triggerAttackRelease("B3", "8n", now + 5)
    sampler.triggerAttackRelease("B3", "4n", now + 5.5)
    sampler.triggerAttackRelease("A3", "8n", now + 6)
    sampler.triggerAttackRelease("A3", "8n", now + 6.5)
    sampler.triggerAttackRelease("G3", "8n", now + 7)

    sampler.triggerAttackRelease("D4", "8n", now + 8)
    sampler.triggerAttackRelease("D4", "4n", now + 8.5)
    sampler.triggerAttackRelease("C4", "8n", now + 9)
    sampler.triggerAttackRelease("C4", "4n", now + 9.5)
    sampler.triggerAttackRelease("B3", "8n", now + 10)
    sampler.triggerAttackRelease("B3", "8n", now + 10.5)
    sampler.triggerAttackRelease("A3", "8n", now + 11)

    sampler.triggerAttackRelease("D4", "8n", now + 12)
    sampler.triggerAttackRelease("D4", "4n", now + 12.5)
    sampler.triggerAttackRelease("C4", "8n", now + 13)
    sampler.triggerAttackRelease("C4", "4n", now + 13.5)
    sampler.triggerAttackRelease("B3", "8n", now + 14)
    sampler.triggerAttackRelease("B3", "8n", now + 14.5)
    sampler.triggerAttackRelease("A3", "8n", now + 15)

    sampler.triggerAttackRelease("G3", "8n", now + 16)
    sampler.triggerAttackRelease("G3", "4n", now + 16.5)
    sampler.triggerAttackRelease("D4", "8n", now + 17)
    sampler.triggerAttackRelease("D4", "4n", now + 17.5)
    sampler.triggerAttackRelease("E4", "8n", now + 18)
    sampler.triggerAttackRelease("E4", "8n", now + 18.5)
    sampler.triggerAttackRelease("D4", "8n", now + 19)

    sampler.triggerAttackRelease("C4", "8n", now + 20)
    sampler.triggerAttackRelease("C4", "4n", now + 20.5)
    sampler.triggerAttackRelease("B3", "8n", now + 21)
    sampler.triggerAttackRelease("B3", "4n", now + 21.5)
    sampler.triggerAttackRelease("A3", "8n", now + 22)
    sampler.triggerAttackRelease("A3", "8n", now + 22.5)
    sampler.triggerAttackRelease("G3", "8n", now + 23)
  }